import type { ChildProfile, RoadmapItem } from '@/lib/types';

function ageString(birthDate: string | null) {
  if (!birthDate) return null;
  const years = Math.floor((Date.now() - new Date(birthDate).getTime()) / (1000 * 60 * 60 * 24 * 365.25));
  return `${years} years old`;
}

const SECTION_TYPES: { title: string; types: RoadmapItem['type'][] }[] = [
  { title: 'Goals', types: ['goal'] },
  { title: 'Recommendations', types: ['recommendation'] },
  { title: 'Key Dates & Milestones', types: ['milestone'] },
  { title: 'What Comes Next', types: ['next_step'] },
];

export function SummaryReport({
  profile,
  items,
}: {
  profile: ChildProfile;
  items: RoadmapItem[];
}) {
  const age = ageString(profile.birth_date ?? null);
  const today = new Date().toLocaleDateString('en-US', { month: 'numeric', day: 'numeric', year: 'numeric' });

  return (
    <div className="rounded-2xl border border-sage-100 bg-white shadow-softer">
      {/* Report header */}
      <div className="border-b border-sage-100 px-6 py-5">
        <p className="text-xs font-medium uppercase tracking-wide text-sage-400">Compass Child Summary</p>
        <p className="mt-0.5 text-xs text-sage-400">Generated {today}</p>
        <h2 className="mt-3 text-xl font-bold text-sage-900">{profile.child_name}</h2>
        {age && <p className="text-sm text-sage-600">{age}</p>}
        <div className="mt-3 space-y-1 text-sm text-sage-700">
          <p>
            <span className="font-medium text-sage-900">Diagnosis: </span>
            {(profile.diagnosis ?? []).join(', ') || 'Not yet specified'}
          </p>
          <p>
            <span className="font-medium text-sage-900">Current services: </span>
            {(profile.current_services ?? []).join(', ') || 'None recorded'}
          </p>
          <p>
            <span className="font-medium text-sage-900">Location: </span>
            {[profile.location_city, profile.location_state, profile.location_zip].filter(Boolean).join(', ') || 'Not specified'}
          </p>
        </div>
      </div>

      {/* Sections */}
      <div className="divide-y divide-sage-50 px-6">
        {SECTION_TYPES.map(({ title, types }) => {
          const rows = items.filter((i) => types.includes(i.type));
          if (rows.length === 0) return null;
          return (
            <div key={title} className="py-5">
              <h3 className="mb-3 text-sm font-semibold text-sage-900">{title}</h3>
              <ul className="space-y-3">
                {rows.map((item) => (
                  <li key={item.id} className="flex gap-2 text-sm">
                    <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-sage-400" />
                    <div>
                      {item.item_date && (
                        <span className="mr-1.5 text-xs text-sage-400">
                          {new Date(item.item_date).toLocaleDateString()} —
                        </span>
                      )}
                      <span className="font-medium text-sage-900">{item.title}</span>
                      {item.description && (
                        <p className="mt-0.5 text-sm text-sage-600">{item.description}</p>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          );
        })}

        {items.length === 0 && (
          <div className="py-8 text-center text-sm text-sage-400">
            Upload a document above to generate your child&apos;s summary.
          </div>
        )}
      </div>

      <div className="border-t border-sage-50 px-6 py-3">
        <p className="text-xs text-sage-300 text-center">
          Generated by Compass — a navigator for parents of autistic and special needs children.
        </p>
      </div>
    </div>
  );
}
