import { NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { requireUser } from '@/lib/auth/requireUser';
import { getCurrentChild } from '@/lib/child/getCurrentChild';
import type { ChildProfile, RoadmapItem } from '@/lib/types';

export const runtime = 'nodejs';

function ageString(birthDate: string | null): string {
  if (!birthDate) return '';
  const dob = new Date(birthDate);
  const months = Math.floor((Date.now() - dob.getTime()) / (1000 * 60 * 60 * 24 * 30.44));
  const years = Math.floor(months / 12);
  return years < 1 ? `${months} months old` : `${years} years old`;
}

function buildPdf(profile: ChildProfile, items: RoadmapItem[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const sage = '#4d7050';
    const dark = '#2d3e2f';

    doc.fillColor(sage).fontSize(22).font('Helvetica-Bold').text('Compass Child Summary');
    doc.moveDown(0.3);
    doc.fillColor(dark).fontSize(11).font('Helvetica').text(`Generated ${new Date().toLocaleDateString()}`);
    doc.moveDown(1);

    doc.fillColor(dark).fontSize(16).font('Helvetica-Bold').text(profile.child_name);
    doc.fontSize(11).font('Helvetica').fillColor(dark).text(ageString(profile.birth_date));
    doc.moveDown(0.5);

    doc.font('Helvetica-Bold').text('Diagnosis: ', { continued: true }).font('Helvetica').text((profile.diagnosis ?? []).join(', ') || 'Not yet specified');
    doc.font('Helvetica-Bold').text('Current services: ', { continued: true }).font('Helvetica').text((profile.current_services ?? []).join(', ') || 'None recorded');
    doc.font('Helvetica-Bold').text('Location: ', { continued: true }).font('Helvetica').text([profile.location_city, profile.location_state, profile.location_zip].filter(Boolean).join(', ') || 'Not specified');
    doc.moveDown(1);

    const sections: { title: string; types: RoadmapItem['type'][] }[] = [
      { title: 'Goals', types: ['goal'] },
      { title: 'Recommendations', types: ['recommendation'] },
      { title: 'Key Dates & Milestones', types: ['milestone'] },
      { title: 'What Comes Next', types: ['next_step'] },
    ];

    for (const section of sections) {
      const rows = items.filter((i) => section.types.includes(i.type));
      if (rows.length === 0) continue;

      doc.fillColor(sage).fontSize(13).font('Helvetica-Bold').text(section.title);
      doc.moveDown(0.2);
      doc.fillColor(dark).fontSize(10).font('Helvetica');
      for (const row of rows) {
        const datePrefix = row.item_date ? `${row.item_date} — ` : '';
        doc.text(`•  ${datePrefix}${row.title}`, { indent: 10 });
        if (row.description) {
          doc.fontSize(9).fillColor('#5b6b5c').text(row.description, { indent: 20 });
          doc.fontSize(10).fillColor(dark);
        }
      }
      doc.moveDown(0.6);
    }

    doc.moveDown(1);
    doc.fontSize(8).fillColor('#8a978b').text('Generated by Compass — a navigator for parents of autistic and special needs children.', { align: 'center' });

    doc.end();
  });
}

export async function GET() {
  const auth = await requireUser();
  if ('error' in auth) return auth.error;
  const { user, supabase } = auth;

  const profile = await getCurrentChild(supabase, user.id);

  if (!profile) {
    return NextResponse.json({ error: 'No child profile found.' }, { status: 400 });
  }

  const { data: items } = await supabase
    .from('roadmap_items')
    .select('*')
    .eq('child_id', profile.id)
    .order('item_date', { ascending: true });

  const pdfBuffer = await buildPdf(profile as ChildProfile, (items ?? []) as RoadmapItem[]);

  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${profile.child_name.replace(/\s+/g, '-')}-compass-summary.pdf"`,
    },
  });
}
